<header class="guide-header">
  <h1>Online Communities</h1>
  <p class="guide-series">Privacy Resources</p>
</header>

<p class="resource-intro">Join and follow these online privacy related communities to engage with others.</p>

<div class="resource-list">

<h3 class="resource-subheading">Reddit Communities</h3>

<div class="resource-item">
  <h3><a href="https://www.reddit.com/r/privacy/" target="_blank" rel="noopener noreferrer">r/privacy</a></h3>
</div>

<div class="resource-item">
  <h3><a href="https://www.reddit.com/r/degoogle/" target="_blank" rel="noopener noreferrer">r/degoogle</a></h3>
</div>

<div class="resource-item">
  <h3><a href="https://www.reddit.com/r/opensource/" target="_blank" rel="noopener noreferrer">r/opensource</a></h3>
</div>

<div class="resource-item">
  <h3><a href="https://www.reddit.com/r/linux/" target="_blank" rel="noopener noreferrer">r/linux</a></h3>
</div>

<div class="resource-item">
  <h3><a href="https://www.reddit.com/r/digitalminimalism/" target="_blank" rel="noopener noreferrer">r/digitalminimalism</a></h3>
  <p>Not a privacy focused subreddit but there is much overlap.</p>
</div>

<h3 class="resource-subheading">Other</h3>

<div class="resource-item">
  <h3><a href="https://discuss.privacyguides.net/" target="_blank" rel="noopener noreferrer">Privacy Guides discussion forum</a></h3>
  <p>Discussion forum for the Privacy Guides community.</p>
</div>


</div>
