name: Scheduled Netlify Build

on:
  schedule:
    # Every 3 hours
    - cron: '17 */3 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify build
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
